server:
  port: 8080

spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/dispatch-db?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    # 重要，开启手动ack，控制消息在MQ中的删除、重发...
    listener: 
      simple: 
        acknowledge-mode: MANUAL
logging:
  level:
    root: warn